# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "master.utf8" ]
  pull_request:
    branches: [ "master.utf8" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download HSP 3.6
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -OutFile ($ENV:GITHUB_WORKSPACE + "\hsp36.zip") https://www.onionsoft.net/hsp/file/hsp36.zip

      - name: Unzip HSP 3.6
        shell: pwsh
        run: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory(($ENV:GITHUB_WORKSPACE + "\hsp36.zip"), ($ENV:GITHUB_WORKSPACE + "\OpenHSP"), [System.Text.Encoding]::GetEncoding("Shift-JIS"))
  
      - name: Build AX of chspcomp
        run: |
          & (${ENV:GITHUB_WORKSPACE} + "\OpenHSP\hsp36\hspcmp.exe") -i -u ("--compath=" + ${ENV:GITHUB_WORKSPACE} + "\OpenHSP\hsp36\common\") ("-o" + ${ENV:GITHUB_WORKSPACE} + "\chspcompu.ax") (${ENV:GITHUB_WORKSPACE} + "\main.hsp")
          
      - name: Build EXE of chspcomp
        run: |
          & (${ENV:GITHUB_WORKSPACE} + "\OpenHSP\hsp36\hsp3c.exe") (${ENV:GITHUB_WORKSPACE} + "\chspcompu.ax") /m (${ENV:GITHUB_WORKSPACE} + "\main.hsp")

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chspcomp
          path: |
            chspcomp.exe
          if-no-files-found: error
